
import Hero from '../components/hero'

export default function Home() {
  return (
    <>
    <Hero/>
     <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi amet neque tempore facere dolorum officiis sint doloremque natus illo, excepturi iste, et maiores quaerat cum consequuntur placeat quas unde fugit voluptatibus ipsam quisquam, dolor error! Amet dignissimos ipsum sit magnam dolore vitae dicta aut vel ratione, illo sequi ea mollitia odit eveniet consectetur rerum cumque saepe autem necessitatibus eligendi repudiandae? Blanditiis, deleniti nesciunt distinctio quo ex qui? Itaque facere quas minus reprehenderit consequuntur quo eum aut voluptatibus. Pariatur quis deserunt facilis harum? Error tenetur, fugit provident voluptas, vero debitis deleniti nihil dolorum possimus pariatur inventore aliquid iusto suscipit. Consequuntur provident error incidunt saepe facilis, ea quisquam molestias soluta, ducimus cupiditate similique cum temporibus corrupti doloremque eligendi quas totam, perferendis deleniti. Temporibus vitae, commodi nemo neque earum debitis amet, blanditiis cumque quidem in laudantium at adipisci voluptates, velit necessitatibus beatae facere tenetur numquam natus cum excepturi obcaecati voluptatem voluptatum! Rem a earum impedit maiores quos, sunt, porro officia distinctio, vero quo iste corrupti voluptate voluptas soluta! Eligendi molestias voluptates consectetur nisi omnis distinctio nesciunt hic earum tempore repudiandae, labore ipsa possimus, ullam quis aliquam corporis ratione iusto, harum odio eum! Odio labore necessitatibus consequatur optio ullam officia ratione. Eos deserunt repellendus nisi earum culpa fuga, aperiam ipsa dolorem eligendi sunt minima saepe iure, obcaecati nemo vitae atque doloremque amet! Nesciunt nostrum reiciendis placeat mollitia ex laudantium cupiditate officiis, omnis recusandae exercitationem sapiente repellat accusantium possimus aliquid corrupti tempora similique aut ratione obcaecati, ab impedit asperiores inventore sequi. Eos ipsam quis tempora praesentium, sed cum culpa cumque, minus quisquam debitis earum non quasi omnis aliquam atque expedita inventore harum deleniti laborum, beatae dolores? Illo, amet praesentium dicta omnis, quidem asperiores quam non numquam, harum corrupti enim. Alias sint eos accusantium, optio soluta assumenda quos nostrum quas ab aliquid quod. Tempore, consectetur provident omnis aspernatur necessitatibus nesciunt architecto inventore quae, veniam voluptates amet ab cupiditate quibusdam quia pariatur, deleniti ut nobis totam iste? Illo sapiente eveniet fugiat nisi nostrum omnis accusantium fuga, necessitatibus sit dolor tenetur!</p>
    </>
  )
}
